# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_manage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1300, 850)
        Dialog.setMinimumSize(QtCore.QSize(900, 600))

        # 使用水平布局
        self.main_layout = QtWidgets.QHBoxLayout(Dialog)
        self.main_layout.setContentsMargins(10, 10, 10, 10)
        self.main_layout.setSpacing(10)

        # 表格
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)

        # 右侧按钮布局
        self.button_layout = QtWidgets.QVBoxLayout()
        self.button_layout.setSpacing(15)
        self.button_layout.setAlignment(QtCore.Qt.AlignTop)

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.button_layout.addWidget(self.pushButton)

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.button_layout.addWidget(self.pushButton_2)

        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setObjectName("pushButton_3")
        self.button_layout.addWidget(self.pushButton_3)

        # 添加弹簧
        self.button_layout.addStretch()

        # 添加到主布局
        self.main_layout.addWidget(self.tableWidget, 1)
        self.main_layout.addLayout(self.button_layout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "用户管理"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "用户ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "用户名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "头像"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "密码"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "编码规则"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "锁定"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "创建时间"))
        self.pushButton.setText(_translate("Dialog", "添加➕"))
        self.pushButton_2.setText(_translate("Dialog", "删除🗑️"))
        self.pushButton_3.setText(_translate("Dialog", "退出✖️"))