# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zhujiemian.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # 使用垂直布局
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(9, 9, 9, 9)
        self.main_layout.setSpacing(6)

        # 工具栏
        self.toolbarWidget = QtWidgets.QWidget(self.centralwidget)
        self.toolbarWidget.setObjectName("toolbarWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolbarWidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.pushButton = QtWidgets.QPushButton(self.toolbarWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setMinimumWidth(100)
        self.pushButton.setMinimumHeight(35)
        self.horizontalLayout.addWidget(self.pushButton)
        
        self.label = QtWidgets.QLabel(self.toolbarWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        
        self.spinBox = QtWidgets.QSpinBox(self.toolbarWidget)
        self.spinBox.setMinimum(1024)
        self.spinBox.setMaximum(65535)
        self.spinBox.setProperty("value", 8000)
        self.spinBox.setMinimumWidth(80)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        
        self.pushButton_2 = QtWidgets.QPushButton(self.toolbarWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setMinimumWidth(110)
        self.pushButton_2.setMinimumHeight(35)
        self.horizontalLayout.addWidget(self.pushButton_2)
        
        self.horizontalLayout.addStretch()  # 添加弹簧，让按钮左对齐

        # 用户列表
        self.userListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.userListWidget.setIconSize(QtCore.QSize(64, 64))
        self.userListWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.userListWidget.setGridSize(QtCore.QSize(80, 90))
        self.userListWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.userListWidget.setObjectName("userListWidget")

        # 日志文本框
        self.logTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setObjectName("logTextEdit")

        # 添加到布局
        self.main_layout.addWidget(self.toolbarWidget)
        self.main_layout.addWidget(self.userListWidget, 2)
        self.main_layout.addWidget(self.logTextEdit, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "安全网络聊天工具 - 服务器"))
        self.pushButton.setText(_translate("MainWindow", "用户管理"))
        self.label.setText(_translate("MainWindow", "监听端口："))
        self.pushButton_2.setText(_translate("MainWindow", "启动/停止"))